// Chat route.
// POST /api/chat — accepts a question and returns an answer generated by the RAG pipeline.

const { Router } = require("express");
const { chatController } = require("../controllers/chat.controller");
const { validate } = require("../../middleware/validation.middleware");
const { chatSchema } = require("../validators/chat.validator");
const { authMiddleware } = require("../../middleware/auth.middleware");

const router = Router();

router.post("/", authMiddleware, validate(chatSchema), chatController.ask);
router.post("/stream", authMiddleware, validate(chatSchema), chatController.askStream);

module.exports = router;
